### ISSUE TITLE
Add headers to "fam.tab" ?

### ISSUE THREAD

**Issue by tseemann** [ncbi/amr#10]
https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinder/data/2019-04-29.1/fam.tab

it would be very useful to add header line to this TSV file.

They are documented here
https://github.com/ncbi/amr/wiki/AMRFinder-database#famtab
but are disconnected from the FTP site.

**Comment by evolarjun** [comment]
It's a good idea, hopefully we'll get that into the next software release.

**Comment by tseemann** [comment]
Thanks Arjun!

**Comment by evolarjun** [comment]
Headers have been added to database [version 2019-10-30.1](https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/3.2/2019-10-30.1/). This database update makes it incompatible with previous versions of the software so we changed our directory format to handle future backwards-incompatible databases and have a [new release](https://github.com/ncbi/amr/releases/tag/amrfinder_v3.2.1) to handle that.
