### ISSUE TITLE
Database requires sofware version at least 3.10.16

### ISSUE THREAD

**Issue by pedrofteixeira** [ncbi/amr#102]
Hello, 

I have just installed the AMRfinder Plus through Bioconda. Once I try to update the database an error occurs:

% amrfinder -u
Running: amrfinder -u
Software directory: '/Users/utilizador/opt/anaconda3/envs/AMRFinder_env/bin/'
Software version: 3.10.1
Running: /Users/utilizador/opt/anaconda3/envs/AMRFinder_env/bin/amrfinder_update -d /Users/utilizador/opt/anaconda3/envs/AMRFinder_env/share/amrfinderplus/data
Looking up databases at https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/
Downloading AMRFinder database version 2022-10-11.2 into '/Users/utilizador/opt/anaconda3/envs/AMRFinder_env/share/amrfinderplus/data/2022-10-11.2/'
Indexing
Database directory: '/Users/utilizador/opt/anaconda3/envs/AMRFinder_env/share/amrfinderplus/data/2022-10-11.2'
Database version: 2022-10-11.2

*** ERROR ***
Database requires sofware version at least 3.10.16
To download the latest version to the default directory run: amrfinder -u

HOSTNAME: ?
SHELL: /bin/zsh
PWD: /Users/utilizador/Documents/REQUIMTE/Genomes/Gardnerella/AllGenomes/FASTA
Progam name:  amrfinder
Command line: amrfinder -u

**Comment by vbrover** [comment]
The current version of AMRFinderPlus in github is 3.10.45.
We will investigate Bioconda.

**Comment by pedrofteixeira** [comment]
Thank you @vbrover

**Comment by evolarjun** [comment]
Hi @pedrofteixeira,

I'm not sure how you got such an old version of AMRFinderPlus, but maybe it's not coming from the correct conda channel? That was the problem for some other people in issue https://github.com/ncbi/amr/issues/81.

Could you try running

```
conda update -c bioconda -c conda-forge ncbi-amrfinderplus
```

And let us know if that installs the current version (3.10.45) and allows you to update with `amrfinder -u`?

You can also check the software version by running `amrfinder -u` .

Thanks!
Arjun

**Comment by vbrover** [comment]
You can check the software version by running `amrfinder --version`.

**Comment by pedrofteixeira** [comment]
Hi @evolarjun, 

I tried updating amrfinder and for some reason it installed the software version 3.10.1. After running amrfinder -u, the same error occurred.

Thank tou,
Pedro Teixeira

**Comment by evolarjun** [comment]
So I am confused by this, but most likely the cause is something else in the environment that is dependent on old versions of BLAST, HMMER, or libcurl. You can try to force a version update like:
```
conda update --force-reinstall -c bioconda -c conda-forge ncbi-amrfinderplus=3.10.45
```
But I'm guessing that will not work.


Another option would be to create a new environment for AMRFinderPlus E.g.:
```
conda create -y -c bioconda -c conda-forge  -n amrfinder ncbi-amrfinderplus=3.10.45
```

Then you'd have to use `conda activate amrfinder` to get into that environment.

Let us know if either of those options work for you.

**Comment by vbrover** [comment]
Another solution would be to install AMRFinderPlus without Conda.

**Comment by evolarjun** [comment]
Installation from binaries is usually pretty easy. The only thing you need is BLAST and HMMER in your path (which you can install with conda if you need to). See https://github.com/ncbi/amr/wiki/Install-with-binary#installing-amrfinderplus-itself for instructions on how to install AMRFinderPlus itself.

**Comment by pedrofteixeira** [comment]
@evolarjun @vbrover I think I just solved this issue. I installed AMRFinderPlus using the Anaconda Navigator and it installed the latest version. Thank you both for your help.

**Comment by evolarjun** [comment]
Glad it worked for you finally. Sorry for the frustrating experience; bioconda doesn't always behave as we expect it to.
