### ISSUE TITLE
Not able to get list of databases in Galaxy

### ISSUE THREAD

**Issue by vmevada102** [ncbi/amr#108]
I have installed Amrfinder Plus in Galaxy.
However, i am not able to get the list of database for the installed tool. Kindly suggest the solution for that.

![IMG_20230128_115511](https://user-images.githubusercontent.com/37470202/215250512-f820a477-3ce1-4f76-940b-af404bf87b35.jpg)

**Comment by vbrover** [comment]
I am not familiar with Galaxy, but if you can run `amrfinder` then to get download/update the AMR genes database please run

    amrfinder -u
