### ISSUE TITLE
AMR_CDS headers not documented (and diff to AMRProt)

### ISSUE THREAD

**Issue by tseemann** [ncbi/amr#12]
The FASTA headers in `AMRProt` are documented here:
https://github.com/ncbi/amr/wiki/AMRFinderPlus-database#amrprot

Example entry:
```
>1000909371|WP_061158039.1
|1|1|blaTEM-156|blaTEM
|hydrolase|class_A_beta-lactamase_TEM-156
```

Example of equivalent entry in `AMR_CDS`:
```
>1000909371|WP_061158039.1
|NG_050200
|1|1|blaTEM-156|blaTEM
|class_A_beta-lactamase_TEM-156 
    NG_050200:101-961
```

They are similar, but different.

Can you document the `AMR_CDS` format like you have `AMRProt` please?

**Comment by vbrover** [comment]
We publish metadata at https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/Data/latest/ReferenceGeneCatalog.txt.

**Comment by tseemann** [comment]
@vbrover yes I am aware of that.  I am asking that you document the `|`-separated columns in `AMR_CDS` just as you do the ones in `AMRProt`. They are not the same.

**Comment by vbrover** [comment]
Do you plan to create your own `AMR_CDS` file to be used in AMRFinder?

**Comment by tseemann** [comment]
I believe AMRFinder(Plus) does not use the `AMR_CDS` file, only the `AMRPriot

I use it for Abricate however: https://github.com/tseemann/abricate

**Comment by evolarjun** [comment]
We should have documentation around the AMR_CDS files. Since we haven't really made much use of them other than a few specific internal purposes I hadn't gotten around to documenting them. I know they are useful and would be more useful with documentation so we'll get on that.

**Comment by vbrover** [comment]
File "AMR_CDS" is a FASTA file of the CDSs of the published AMR proteins.
Sequence names are followed by: <DNA accession>:<start>-<stop>
A sequence name is a | -delimited string with elements:
- protein GI
- protein accession
- DNA accession
- fusion part number
- total # of fusion parts in the protein (1 if the protein is not a fusion)
- family_id
- family parent if the protein is an allele, or family_id otherwise
- family name

**Comment by evolarjun** [comment]
Done, see https://github.com/ncbi/amr/wiki/AMRFinderPlus-database#amr_cds.  Thanks!

**Comment by tseemann** [comment]
That's perfect @evolarjun and @vbrover   - thank you.
