### ISSUE TITLE
Minor typo in wiki

### ISSUE THREAD

**Issue by jvhagey** [ncbi/amr#121]
Hi, 

Just wanted to flag a very minor issue. In the wiki under [--organism option](https://github.com/ncbi/amr/wiki/Running-AMRFinderPlus#--organism-option) in the `Organism Option` column `Burhkholderia_pesudomallei` is spelled incorrectly and should be `Burkholderia_pseudomallei`. I just copied and pasted for a script and ended up with an error. Thanks!

**Comment by vbrover** [comment]
Thank you!
The correct list of organisms can be obtained by

````
$ amrfinder --list_organisms -q
Available --organism options: Acinetobacter_baumannii, Burkholderia_cepacia, Burkholderia_pseudomallei, Campylobacter, Citrobacter_freundii, Clostridioides_difficile, Enterobacter_cloacae, Enterococcus_faecalis, Enterococcus_faecium, Escherichia, Klebsiella_oxytoca, Klebsiella_pneumoniae, Neisseria_gonorrhoeae, Neisseria_meningitidis, Pseudomonas_aeruginosa, Salmonella, Serratia_marcescens, Staphylococcus_aureus, Staphylococcus_pseudintermedius, Streptococcus_agalactiae, Streptococcus_pneumoniae, Streptococcus_pyogenes, Vibrio_cholerae
````

**Comment by evolarjun** [comment]
Hi @jvhagey, 

It was my fat fingers, but it's now fixed thanks to you.
