### ISSUE TITLE
Multiple result

### ISSUE THREAD

**Issue by LuisSolisLxr** [ncbi/amr#125]
Hi, I want to know how can I run multiple genomes using FASTA format, because I use this command but doesn´t work.

amrfinder --plus --nucleotide *.fasta -O Streptococcus_pneumoniae > results.csv

*** ERROR ***
"10060_1#11.fasta" cannot be a positional parameter

Identify AMR and virulence genes in proteins and/or contigs and print a report

DOCUMENTATION
    See https://github.com/ncbi/amr/wiki for full documentation

UPDATES
    Subscribe to the amrfinder-announce mailing list for database and software update notifications:
    https://www.ncbi.nlm.nih.gov/mailman/listinfo/amrfinder-announce

USAGE:   amrfinder [--update] [--force_update] [--protein PROT_FASTA] [--nucleotide NUC_FASTA] [--gff GFF_FILE] [--pgap] [--annotation_format ANNOTATION_FORMAT] [--database DATABASE_DIR] [--ident_min MIN_IDENT] [--coverage_min MIN_COV] [--organism ORGANISM] [--list_organisms] [--translation_table TRANSLATION_TABLE] [--plus] [--report_common] [--mutation_all MUT_ALL_FILE] [--blast_bin BLAST_DIR] [--hmmer_bin HMMER_DIR] [--report_all_equal] [--print_node] [--name NAME] [--output OUTPUT_FILE] [--protein_output PROT_FASTA_OUT] [--nucleotide_output NUC_FASTA_OUT] [--nucleotide_flank5_output NUC_FLANK5_FASTA_OUT] [--nucleotide_flank5_size NUC_FLANK5_SIZE] [--quiet] [--gpipe_org] [--parm PARM] [--database_version] [--threads THREADS] [--debug] [--log LOG]
HELP:    amrfinder --help or amrfinder -h
VERSION: amrfinder --version

HOSTNAME: ?
SHELL: /bin/bash
PWD: /home/luis/Documents/amresult/prueba
PATH: /home/luis/miniconda3/envs/amrfinder/bin:/home/luis/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
Progam name:  amrfinder

**Comment by vbrover** [comment]
````
for ASM in *.fasta; do amrfinder --plus -n $ASM -O Streptococcus_pneumoniae; done > results.csv
````
See also https://github.com/ncbi/amr/wiki/Tips-and-tricks#use-a-bash-loop-to-run-on-a-number-of-files-serially

**Comment by LuisSolisLxr** [comment]
Thank you so much.
