### ISSUE TITLE
amrfinder running with options --ident_min and --coverage_min

### ISSUE THREAD

**Issue by stalact** [ncbi/amr#126]
Hi all, 
I want to run amrfinder with minimum identity of 80% and a coverage of 90%: 

Running: amrfinder -n genome.fna --ident_min 0.8 --coverage_min 0.9 -o genome.tsv

A gene listed with 55% Identity to reference sequence. 
Are the arguments passed properly? This gene should not be listed, since the minimum should be 80% identy? 
The same issue occurs with the protein option. 

Thanks for your help :-)

**Comment by evolarjun** [comment]
Resolving since we don't have test data. Please reopen and include test data if this is still an issue.
