### ISSUE TITLE
Literature reference for aac(6')-Ib3

### ISSUE THREAD

**Issue by kalilamali** [ncbi/amr#128]
Hi,
Could I get the reference to the literature used for:
| Gene symbol  | Subclass |
| ------------- | ------------- |
| aac(6')-Ib3   |  AMIKACIN/KANAMYCIN/TROBAMYCIN |

The reference from the nucleotide acc (https://www.liebertpub.com/doi/10.1089/10766290260469516) states intermedium amikacin resistance but on this other paper the gene contribution seems limited:
"Deleting acc (6′)-Ib3 had a more marked effect, increasing tobramycin and gentamicin sensitivity by 64- and 16-fold, respectively, and lowering the MICs below clinical resistance breakpoints while having no effect on amikacin resistance."
 https://www.mdpi.com/2079-6382/11/7/884
Thanks in advance,
Karen.

**Comment by vbrover** [comment]
All genes are in the "Reference Gene Catalog": https://www.ncbi.nlm.nih.gov/pathogens/refgene/#aac(6')-Ib3
Add the column "Pubmed reference".
It will point to https://pubmed.ncbi.nlm.nih.gov/9579076/.

**Comment by evolarjun** [comment]
Hi Karen,

Our primary aminoglycoside curator is on vacation right now, but for many of the genes you can get to the references used to fill out the phenotype information from our [Reference Gene Catalog](https://www.ncbi.nlm.nih.gov/pathogens/refgene/#aac(6')-Ib3). You may have to click the "Choose columns" button and add the "Pubmed reference" column to the display to see it. In this case the reference PMID for [WP_032488579.1](https://www.ncbi.nlm.nih.gov/pathogens/refgene/#WP_032488579.1) (aac(6')-Ib3) is [9579076](https://www.ncbi.nlm.nih.gov/pubmed/9579076)

Thanks for your question, and I'll ping our curator when he gets back.

Arjun

**Comment by kalilamali** [comment]
Thank you so much for the very detailed and insightful answer!
