### ISSUE TITLE
point mutation in Enterobacter spp

### ISSUE THREAD

**Issue by Juandemendieta** [ncbi/amr#129]
Hello... I would like to know if you can give me a hand... I am trying to obtain the point mutations (-O) for Enterobacter spp assemblies, but I cannot do it since Enterobacter does not appear in the list of organisms for this command, although amrfinder is supposed to be able to do it for this genus. Could someone guide me?

**Comment by vbrover** [comment]
There are `Enterobacter_asburiae` and `Enterobacter_cloacae`.
````
$ amrfinder  --list_organisms 

Available --organism options: Acinetobacter_baumannii, Burkholderia_cepacia, Burkholderia_pseudomallei, Campylobacter, Citrobacter_freundii, Clostridioides_difficile, Enterobacter_asburiae, Enterobacter_cloacae, Enterococcus_faecalis, Enterococcus_faecium, Escherichia, Klebsiella_oxytoca, Klebsiella_pneumoniae, Neisseria_gonorrhoeae, Neisseria_meningitidis, Pseudomonas_aeruginosa, Salmonella, Serratia_marcescens, Staphylococcus_aureus, Staphylococcus_pseudintermedius, Streptococcus_agalactiae, Streptococcus_pneumoniae, Streptococcus_pyogenes, Vibrio_cholerae
````

**Comment by Juandemendieta** [comment]
Thanks for the reply. 
A smaller list appears in the amrfinder installed on my institution's server:
'Available --organism options: Acinetobacter_baumannii, Burkholderia_cepacia, Burkholderia_pseudomallei, Campylobacter, Clostridioides_difficile, Enterococcus_faecalis, Enterococcus_faecium, Escherichia, Klebsiella, Neisseria, Pseudo monas_aeruginosa, Salmonella, Staphylococcus_aureus, Staphylococcus_pseudintermedius, Streptococcus_agalactiae, Streptococcus_pneumoniae, Streptococcus_pyogenes, Vibrio_cholerae'


How can the databases of the other species be incorporated?

**Comment by vbrover** [comment]
This will update the database: `amrfinder -u`

**Comment by vbrover** [comment]
The latest software version: 3.11.14
The latest database version: 2023-07-13.2

**Comment by Juandemendieta** [comment]
Thank you very much.. with the latest version of the software it was solved..
