### ISSUE TITLE
Confusion regarding fusion gene part numbers

### ISSUE THREAD

**Issue by tseemann** [ncbi/amr#13]
The docs say:
```
Fusion gene part number, 1 if not a fusion gene
Total number of fusion parts, 1 if not a fusion gene
```
An example from `AMRProt`:
```
>446950888|WP_001028144.1|1|2|aac(6')-Ie|aac(6')-Ie|
>446950888|WP_001028144.1|2|2|aph(2'')-Ia|aph(2'')-Ia|
```
The first gene above is the 1st in the fusion of 2 genes, so it has `1`.
But your docs suggest that means it is _not_ a fusion gene.

I guess you mean if it is `|1|1|` then it is not a fusion gene?
Like it is "part 1 of 1"?

**Comment by evolarjun** [comment]
> I guess you mean if it is |1|1| then it is not a fusion gene?
> Like it is "part 1 of 1"?

You are correct. I tried to clarify the description in the documentation. See https://github.com/ncbi/amr/wiki/AMRFinderPlus-database#amrprot
