### ISSUE TITLE
Is it possible to get the abundance of each AMR?

### ISSUE THREAD

**Issue by pedres** [ncbi/amr#133]
Hi, 
I was reading the documentation and open/closed issues but I cannot find if it is possible or not to get the counts of each detected AMR with AMRFinderPlus
Thanks a lot for your help,

Manuel

**Comment by evolarjun** [comment]
Hi Manuel,

I think that should be easy to do with some simple shell, but I'm curious as to what you're trying to do because I'm not sure it makes sense in the way I think about running AMRFinderPlus. Could you elaborate on what your goal is because I may not understand what you're trying to do.

Thanks,
Arjun

**Comment by pedres** [comment]
Hi Arjun,

Thanks for your fast answer. We have a set of data (sewage sludge, earthworm faeces and vermicompost) and we have run AMRFinderPlus. It detects AMR genes, some of them are specific for each sample type but others appear in all sample types and we would like to do some differential abundance testing to know whether earthworm reduce them.
Another question is how the --organism option works. From documentation, I understand that the program looks only for AMR genes specific for that bacteria. However, I have run AMRFinder with these commands and the output is the same:
amrfinder -n ss-1_945729_contigs.fasta	--organism Acinetobacter_baumannii --threads 20 --name ss1 --plus > ss1_Acinetobacter_baumannii.amrfinder
amrfinder -n ss-1_945729_contigs.fasta	--organism Klebsiella_oxytoca --threads 20 --name ss1 --plus > ss1_Klebsiella_oxytoca.amrfinder
amrfinder -n ss-1_945729_contigs.fasta	--organism Clostridioides_difficile --threads 20 --name ss1 --plus > ss1_Clostridioides_difficile.amrfinder

What I am doing wrong?
Thank you very much for your help.

Manuel

**Comment by vbrover** [comment]
If the option `--organism ORG` is used then
- the point mutations (in proteins and in DNA) specific to this ORG are included on the AMRFinderPlus output;
- the AMR proteins common to ORG are not included on the AMRFinderPlus output.

The output of AMRFinderPlus is a table which can be used for further data analysis.

**Comment by pedres** [comment]
Hi Arjun,

Yes we have metagenomic assemblies. Thanks again for your explanation. Our sequencer provider gives us the assembly and the AMR output from AMRFinderPlus, so  I run it again to understand how it works. I will contact them asking them if this the more suitable option. We have protein sequences but only for individual bin/MAGs not for the whole assembly.

Thanks again,

Manuel

**Comment by pedres** [comment]
Hi Arjun,

I check the example of cut command and it was not I was looking for. I would like to know how many times each of the AMRs dectected by AMRFinderPlus occurs in the assembly. For example, I have tried the resistomeanalyzer that works great with sam files.

**Comment by vbrover** [comment]
Would you like to have AMRFinderPlus output the same way as `resistomeanalyzer` does?
What is the output of `resistomeanalyzer `?

**Comment by evolarjun** [comment]
Hi Manuel,

AMRFinderPlus is very different from resistomeanalyzer. It does not align reads and doesn't take a SAM file, so it won't detect how many reads align or bases are covered. AMRFinderPlus will accurately identify and name AMR genes, but it does not count reads, alignments, or covered bases.

Good luck,
Arjun
