### ISSUE TITLE
No POINT results in combine PROT+NUCL mode

### ISSUE THREAD

**Issue by bvalot** [ncbi/amr#134]
Hi,

I have a strange results with amrfinderplus.
When I use only nucleotide input, I get POINT mutation results.
When I make combine mode -n -p -g with nucleotide and protein, the POINT mutations disappear on the results for the same input.

Do I miss some options?

Thanks in advance
Benoit

Software version: 3.11.26
Database version: 2023-11-15.1

**Comment by vbrover** [comment]
Please post complete command lines and the input files.

**Comment by bvalot** [comment]
`amrfinder -d ~/database/amrfinder/latest -n assembly/E118_S138.fna -O Escherichia -o amrfinder/E118_S138`

`amrfinder -d ~/database/amrfinder/latest -n assembly/1900620242.fna -O Pseudomonas_aeruginosa -p annotation/1900620242_ok.faa -g annotation/1900620242_ok.gff -o amrfinder/1900620242_combi`

**Comment by bvalot** [comment]
For the files:
https://filesender.renater.fr/?s=download&token=d2b17339-a0db-46a1-94f9-4d1a65ae31bd

**Comment by bvalot** [comment]
Ah! Sorry. Just see that I use bad -O options...

**Comment by vbrover** [comment]
Point mutations are species-specific.
What is the species of the assembly E118_S138?

**Comment by bvalot** [comment]
It is Escherichia coli. Just make error on copy/paste :)
