### ISSUE TITLE
Errors using gff3 file from bakta 

### ISSUE THREAD

**Issue by minjaekim45** [ncbi/amr#141]
Hello amrfinderplus,

Thank you very much for your effort!
I've encountered error to run amrfinderplus using gff3 file created from bakta.
_GFF file mismatch.
*** ERROR ***
gff_check.cpp: GFF contig id "contig_1" is not in the DNA FASTA file_
This is my commandline for running amrfinderplus
amrfinder --protein P_aeruginosa_AST.faa --nucleotide P_aeruginosa_AST.ffn -g P_aeruginosa_AST.gff3 -O Pseudomonas_aeruginosa --plus -a bakta

**And this is the output from head command of P_aeruginosa_AST.gff3**
##gff-version 3
##feature-ontology https://github.com/The-Sequence-Ontology/SO-Ontologies/blob/v3.1/so.obo
# Annotated with Bakta
# Software: v1.9.3
# Database: v5.1, full
# DOI: 10.1099/mgen.0.000685
# URL: github.com/oschwengers/bakta
##sequence-region contig_1 1 6604386
contig_1        Bakta   region  1       6604386 .       +       .       ID=contig_1;Name=contig_1
contig_1        Prodigal        CDS     979     1692    .       +       0       ID=EIOJLK_00005;Name=quorum-sensing transcriptional repressor QscR;locus_tag=EIOJLK_00005;product=quorum-sensing transcriptional repressor QscR;Dbxref=BlastRules:WP_003118960,COG:COG2197,COG:TK,RefSeq:WP_003118960.1,SO:0001217,UniParc:UPI00000D4284,UniRef:UniRef100_Q9RMS5,UniRef:UniRef50_Q9RMS5,UniRef:UniRef90_Q9RMS5;gene=qscR

**And this is the first 5lines of my ffn file**
>EIOJLK_00005 quorum-sensing transcriptional repressor QscR
ATGCATGATGAGAGAGAGGGATATCTCGAGATTTTGTCAAGAATAACAACCGAGGAAGAGTTCTTCTCCCTGGTTCTCGAGATATGCGGTAATTATGGATTCGAATTCTTTTCATTCGGTGCGCGGGCGCCTTTCCCGCTGACCGCGCCTAAATATCATTTCTTGTCCAATTACCCAGGGGAATGGAAAAGCAGATATATCTCCGAAGACTACACATCCATCGACCCGATCGTGCGCCATGGTCTCCTGGAATACACCCCGCTGATCTGGAATGGCGAAGACTTCCAGGAGAACCGTTTCTTCTGGGAGGAAGCGCTGCATCACGGCATCCGTCACGGCTGGTCGATCCCGGTCCGCGGCAAGTACGGGCTGATCAGCATGCTGTCCCTGGTGCGTTCCAGCGAGAGCATCGCCGCCACGGAAATCCTGGAGAAGGAATCCTTCCTGCTCTGGATCACCAGCATGCTGCAGGCTACCTTCGGCGACCTGCTGGCGCCGCGCATCGTTCCGGAAAGCAATGTGCGCCTGACCGCCAGGGAAACCGAGATGCTCAAGTGGACCGCGGTGGGCAAGACCTACGGCGAGATCGGCCTGATCCTGTCGATCGACCAGCGCACGGTGAAATTCCATATCGTCAATGCGATGCGCAAGCTCAACTCCAGCAACAAGGCGGAGGCCACCATGAAGGCCTACGCCATCGGCCTGCTCAACTGA
>EIOJLK_00010 phenazine biosynthesis protein PhzA
ATGCGAGAGTACCAACGGTTGAAAGGGTTTACCGACAACCTGGAATTACGGCGGCGCAACCGTGCCACGGTCGAGCACTACATGCGCATGAAGGGGGCCGAACGGTTGCAGCGGCACAGCCTGTTCGTCGAGGACGGCTGCGCCGGCAACTGGACCACGGAAAGCGGTGAACCCCTGGTTTTCCGGGGCCATGAGAGCCTCAGGCGGCTCGCCGAGTGGCTCGAGCGCTGCTTCCCCGACTGGGAGTGGCACAACGTGCGGATCTTCGAGACCGAGGATCCGAACCACTTCTGGGTCGAGTGCGACGGGCGCGGCAAGGCGCTGGTCCCGGGGTATCCGCAGGGCTATTGCGAGAACCACTACATCCATTCCTTCGAACTCGAGAACGGCCGGATAAAACGCAATCGCGAGTTCATGAACCCGATGCAGAAATTGCGTGCATTGGGAATAGCCGTTCCGCAAATAAAACGTGACGGCATTCCCACCTGA
>EIOJLK_00015 phenazine biosynthesis protein PhzB

**And this is the head -5 of my faa file**
>EIOJLK_00005 quorum-sensing transcriptional repressor QscR
MHDEREGYLEILSRITTEEEFFSLVLEICGNYGFEFFSFGARAPFPLTAPKYHFLSNYPGEWKSRYISEDYTSIDPIVRHGLLEYTPLIWNGEDFQENRFFWEEALHHGIRHGWSIPVRGKYGLISMLSLVRSSESIAATEILEKESFLLWITSMLQATFGDLLAPRIVPESNVRLTARETEMLKWTAVGKTYGEIGLILSIDQRTVKFHIVNAMRKLNSSNKAEATMKAYAIGLLN
>EIOJLK_00010 phenazine biosynthesis protein PhzA
MREYQRLKGFTDNLELRRRNRATVEHYMRMKGAERLQRHSLFVEDGCAGNWTTESGEPLVFRGHESLRRLAEWLERCFPDWEWHNVRIFETEDPNHFWVECDGRGKALVPGYPQGYCENHYIHSFELENGRIKRNREFMNPMQKLRALGIAVPQIKRDGIPT
>EIOJLK_00015 phenazine biosynthesis protein PhzB

Thanks!
Minjae

**Comment by vbrover** [comment]
> EIOJLK_00005 quorum-sensing transcriptional repressor QscR
> ATGCATGATGAGAGAGAGGGATATCTCGAGATTTTGTCAAGAATAACAACCGAGGAAGAGTTCTTCTCCCTGGTTCTCGAGATATGCGGTAA
> ...

This looks like a CDS file (file with only codign segments).
The expected file should be like

    >Contig_1 ...
    ATGCATGATGAGAGAGAGGGATATCTCGAGATTTTGTCAAGAATAACAACCGAGGAAGAGTTCTTCTCCCTGGTTCTCGAGATATGCGGTAA
    ...

**Comment by vbrover** [comment]
> So, you're suggesting manually adding "contig_1" at the beginning of every FASTA header?

No, I am suggesting to find the correct file produced by `bakta`.

**Comment by minjaekim45** [comment]
Thank you so much for the clarification!
That was my oversight putting predicted gene file rather than the assembly file.

**Comment by evolarjun** [comment]
@minjaekim45 Glad it's working for you now!  Let us know if you have other issues or questions.
