### ISSUE TITLE
Some AMR genes don't are detected in my contigs data.

### ISSUE THREAD

**Issue by MicSonn** [ncbi/amr#146]
Hi,

Thanks for this very useful tool.

I run amrfinder v3.12.8 with db v2024-01-31.1 on Acinetobacter_baumannii as organism.

Some genes as adeA/adeB,.../adeS and mrcB and some others don't are detected. If I Run Blastn on my contigs the above genes are detected properly.

Could you help me understand why?

Best regards,
Michele

**Comment by vbrover** [comment]
Are you using the `--plus` option?

**Comment by vbrover** [comment]
Could you post the input files and the complete AMRFinderPlus command you are using?

**Comment by MicSonn** [comment]
amrfinder --threads 15 --plus --name Acinetobacter --nucleotide contigs.fasta --organism Acinetobacter_baumannii --output ./ --mutation_all ./mut.txt --nucleotide_output ./nucl.txt

The multifasta file and Data Analysis are being published, I can't share it for the moment. However, it is correctly formatted as a multifasta as SPades output. In total, 30 samples were analyzed.

**Comment by vbrover** [comment]
> Some genes as adeA/adeB,.../adeS and mrcB and some others don't are detected. If I Run Blastn on my contigs the above genes are detected properly.

Are these genes in the AMRFinderPlus database?

AMRFinderPlus is supposed to cover _all_ AMR genes and _some_ virulence genes.

**Comment by MicSonn** [comment]
I haven't checked the db, I imagine these genes are not present. In fact my question is why aren't they present?

I'll check the db carefully

**Comment by MicSonn** [comment]
Thanks for now, see you tomorrow.

**Comment by evolarjun** [comment]
The AMRFinderPlus database should cover known phenotypically important acquired AMR genes and notable virulence and stress resistance genes for certain curated taxa. A full list of the genes included in AMRFinderPlus can be seen in the Reference Gene Hierarchy at https://www.ncbi.nlm.nih.gov/pathogens/genehierarchy/

The Reference Gene Catalog at https://www.ncbi.nlm.nih.gov/pathogens/refgene/ lists all protein references and point mutations included in the database.

**Comment by MicSonn** [comment]
Perfect!!!
Thank you very much
