### ISSUE TITLE
Cronobacter and Listeria in list but still throws error

### ISSUE THREAD

**Issue by jibrantahir** [ncbi/amr#150]
The 'https://github.com/ncbi/amr/wiki/Curated-organisms' states 'Cronobacter' in list but its usage in amr throws error- it works fine without mentioning its name in '-O' though!

amrfinder --annotation_format prokka -p  test8.protein.fa -g test8.prokka.gff -n test8.medaka.fa --organism Cronobacter -o 8.tsv

OR

amrfinder --annotation_format prokka -p  test8.protein.fa -g test8.prokka.gff -n test8.medaka.fa -O Cronobacter -o 8.tsv

The result is same as below;

Running: amrfinder --annotation_format prokka -p test8.protein.fa -g test8.prokka.gff -n test8.medaka.fa --organism Cronobacter -o 8.tsv
Software directory: '/home/micro/miniconda3/envs/amrfinder/bin/'
Software version: 3.12.8
Database directory: '/home/micro/miniconda3/envs/amrfinder/share/amrfinderplus/data/2024-07-22.1'
Database version: 2024-07-22.1
AMRFinder combined translated and protein and mutation search

*** ERROR ***
Possible organisms: Acinetobacter_baumannii, Burkholderia_cepacia, Burkholderia_mallei, Burkholderia_pseudomallei, Campylobacter, Citrobacter_freundii, Clostridioides_difficile, Corynebacterium_diphtheriae, Enterobacter_asburiae, Enterobacter_cloacae, Enterococcus_faecalis, Enterococcus_faecium, Escherichia, Klebsiella_oxytoca, Klebsiella_pneumoniae, Neisseria_gonorrhoeae, Neisseria_meningitidis, Pseudomonas_aeruginosa, Salmonella, Serratia_marcescens, Staphylococcus_aureus, Staphylococcus_pseudintermedius, Streptococcus_agalactiae, Streptococcus_pneumoniae, Streptococcus_pyogenes, Vibrio_cholerae, Vibrio_parahaemolyticus, Vibrio_vulnificus

HOSTNAME: ?
SHELL: /bin/bash
PWD: /home/micro/ONT_Runs/ONT_Analysis/2024/wgs5/output/test8
PATH: /home/micro/miniconda3/envs/amrfinder/bin:/home/micro/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/bin/remote-cli:/home/micro/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/micro/dorado-0.8.0-linux-x64/bin:/home/micro/dorado-0.8.0-linux-x64/bin
Progam name:  amrfinder
Command line: amrfinder --annotation_format prokka -p test8.protein.fa -g test8.prokka.gff -n test8.medaka.fa --organism Cronobacter -o 8.tsv         

Same is the issue with Listeria - its present 'https://github.com/ncbi/amr/wiki/Curated-organisms'

amrfinder --annotation_format prokka -p  test9.protein.faa -g test9.prokka.gff -n test9.medaka.fasta --organism Listeria monocytogenes -o 9.tsv

*** ERROR ***
"monocytogenes" cannot be a positional parameter

Identify AMR and virulence genes in proteins and/or contigs and print a report

DOCUMENTATION
    See https://github.com/ncbi/amr/wiki for full documentation

UPDATES
    Subscribe to the amrfinder-announce mailing list for database and software update notifications:
    https://www.ncbi.nlm.nih.gov/mailman/listinfo/amrfinder-announce

USAGE:   amrfinder [--update] [--force_update] [--protein PROT_FASTA] [--nucleotide NUC_FASTA] [--gff GFF_FILE] [--annotation_format ANNOTATION_FORMAT] [--database DATABASE_DIR] [--database_version] [--ident_min MIN_IDENT] [--coverage_min MIN_COV] [--organism ORGANISM] [--list_organisms] [--translation_table TRANSLATION_TABLE] [--plus] [--report_common] [--report_all_equal] [--name NAME] [--print_node] [--mutation_all MUT_ALL_FILE] [--output OUTPUT_FILE] [--protein_output PROT_FASTA_OUT] [--nucleotide_output NUC_FASTA_OUT] [--nucleotide_flank5_output NUC_FLANK5_FASTA_OUT] [--nucleotide_flank5_size NUC_FLANK5_SIZE] [--blast_bin BLAST_DIR] [--hmmer_bin HMMER_DIR] [--quiet] [--pgap] [--gpipe_org] [--parm PARM] [--threads THREADS] [--debug] [--log LOG]
HELP:    amrfinder --help or amrfinder -h
VERSION: amrfinder --version

HOSTNAME: ?
SHELL: /bin/bash
PWD: /home/micro/ONT_Runs/ONT_Analysis/2024/wgs5/output/test9
PATH: /home/micro/miniconda3/envs/amrfinder/bin:/home/micro/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/bin/remote-cli:/home/micro/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/micro/dorado-0.8.0-linux-x64/bin:/home/micro/dorado-0.8.0-linux-x64/bin
Progam name:  amrfinder
Command line: amrfinder --annotation_format prokka -p test9.protein.faa -g test9.prokka.gff -n test9.medaka.fasta --organism Listeria monocytogenes -o 9.tsv

The database is latest:
amrfinder --update
Running: amrfinder --update
Software directory: '/home/micro/miniconda3/envs/amrfinder/bin/'
Software version: 3.12.8
Running: /home/micro/miniconda3/envs/amrfinder/bin/amrfinder_update -d /home/micro/miniconda3/envs/amrfinder/share/amrfinderplus/data
Looking up the published databases at https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/
Looking for the target directory /home/micro/miniconda3/envs/amrfinder/share/amrfinderplus/data/2024-07-22.1/
WARNING: '/home/micro/miniconda3/envs/amrfinder/share/amrfinderplus/data/2024-07-22.1/' contains the latest version: 2024-07-22.1
Skipping update, use amrfinder --force_update to overwrite the existing database
Database directory: '/home/micro/miniconda3/envs/amrfinder/share/amrfinderplus/data/2024-07-22.1'
Database version: 2024-07-22.1

**Comment by evolarjun** [comment]
Hi Jibran,

Sorry it isn't clear. The https://github.com/ncbi/amr/wiki/Curated-organisms table is a list of organisms that our curators have looked at and are fairly confident we have good representation of the genes in the various classes. You don't need to specify a taxon for AMRFinderPlus to identify those genes. The genes are all searched against all taxa by default. Run `amrfinder --list_organisms` to get a list of the organism options that are available. The --organism option is used to select references for point mutations, and in a few cases suppress reporting universal genes that don't have an effect on phenotype in one specific taxon.

See also the documentation for the `--organism option` at https://github.com/ncbi/amr/wiki/Running-AMRFinderPlus#--organism-option

Let us know if you have more questions,
Arjun
