### ISSUE TITLE
Error fasta_check status 256

### ISSUE THREAD

**Issue by apoosakkannu** [ncbi/amr#151]
I am having following error,

Running: /projappl/project_2003832/amrfinder-3.12.8/bin/amrfinder -n /scratch/project_2003832/shotgun/arg_search/samples_ncbi_contigs_all_mod.fasta --plus --threads 40 -d /scratch/project_2003832/shotgun/arg_search/amrfinder_db/latest
Software directory: '/usr/local/bin/'
Software version: 3.12.8
Database directory: '/scratch/project_2003832/shotgun/arg_search/amrfinder_db/2024-07-22.1'
Database version: 2024-07-22.1
AMRFinder translated nucleotide search
  - include -O ORGANISM, --organism ORGANISM option to add mutation searches and suppress common proteins

*** ERROR ***
'/usr/local/bin/fasta_check' '/scratch/project_2003832/shotgun/arg_search/samples_ncbi_contigs_all_mod.fasta'  -len /tmp/poosakka/23838353/amrfinder.LXxdpg/len  -hyphen  -ambig  -log /tmp/poosakka/23838353/amrfinder.LXxdpg/log > /tmp/poosakka/23838353/amrfinder.LXxdpg/nseq
status = 256

HOSTNAME: r01c18
SHELL: /bin/bash
PWD: /scratch/project_2003832/shotgun/arg_search
PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Progam name:  amrfinder
Command line: /projappl/project_2003832/amrfinder-3.12.8/bin/amrfinder -n /scratch/project_2003832/shotgun/arg_search/samples_ncbi_contigs_all_mod.fasta --plus --threads 40 -d /scratch/project_2003832/shotgun/arg_search/amrfinder_db/latest

Please give me an ide to overcome this problem.

**Comment by vbrover** [comment]
Something is wrong with the input FASTA file `/scratch/project_2003832/shotgun/arg_search/samples_ncbi_contigs_all_mod.fasta`.
Please 

    cat /tmp/poosakka/23838353/amrfinder.LXxdpg/nseq

**Comment by apoosakkannu** [comment]
Thanks. 

Update: I created temporary directory and it worked fine.

**Comment by evolarjun** [comment]
@apoosakkannu, just to confirm I understand how you fixed the issue: It turned out that the problem was the temporary directory didn't exist and that's why the file read error?

It sounds like the error message wasn't particularly helpful of finding the root cause of the issue. We'll discuss better handling when the temporary directory doesn't exist. I'm not sure that's an issue I anticipated :-) 

Thanks for reporting and letting us know what the issue was when you found it.

**Comment by apoosakkannu** [comment]
My service desk suggested the following,
There is also the possibility of the error coming from /tmp filling up,
so there is a chance that setting $TMPDIR will even solve the issue.

I tried it and it working now,
