### ISSUE TITLE
AMR Element in core/plus scope only reported with --plus settings

### ISSUE THREAD

**Issue by Calebros** [ncbi/amr#152]
I am running AMRFinder Plus in Linux from a Conda installation.  Software version: "3.12.8" Database version: "2024-07-22.1".  

Using the commands
"amrfinder -n curatedInput.fasta -o allcontigs-noplus.txt"
"amrfinder -n curatedInput.fasta --plus -o allcontigs-plus.txt"

Core output results are no AMR genes.
Plus output results include 1 beta-lactam AMR element.

I am specifically concerned or puzzled by blaEC hits absense for the core-only results  The database https://www.ncbi.nlm.nih.gov/pathogens/genehierarchy/#blaEC shows the parental blaEC node ID as "plus scope", while some sub-nodes (in my case blaEC-15) are listed as core, but weren't reported unless --plus was invoked.

Would someone be willing to advise?

1. Is this intended behavior within the reference gene hierarchy?
2.  Is it always recommended to run plus over core to avoid these potential situations?

Thank you for your time, it is greatly appreciated

[allcontigs-noplus.txt](https://github.com/user-attachments/files/17402821/allcontigs-noplus.txt)
[allcontigs-plus.txt](https://github.com/user-attachments/files/17402825/allcontigs-plus.txt)

**Comment by vbrover** [comment]
> some sub-nodes (in my case blaEC-15) are listed as core, but weren't reported unless --plus was invoked.
> 1. Is this intended behavior within the reference gene hierarchy?

Yes.
An allele is present in the genome iff it is 100% identical to the whole reference sequence.
So, no known bleEC allele is present (column "Gene symbol" reports "blaEC", but not, for example, "blaEC-15"; and column "Method" says "BLASTX", but not "ALLELE").
So, indeed, in the submitted genome there are no "core" genes, but there are "plus" genes.

> 2. Is it always recommended to run plus over core to avoid these potential situations?

If you need only "core" genes - with established AMR functionality, do not use the `--plus` option.
If you need genes with approximate AMR functionality, use the `--plus` option and also look at the "Scope" column.

**Comment by Calebros** [comment]
Thank you for the explanation, much appreciated.

**Comment by evolarjun** [comment]
Hi @Calebros ,

To clarify a little further, your average chromosmal blaEC generally does not affect resistance phenotype so they are categorized in the "plus" set. There are a few named alleles of blaEC such as the blaEC-15 that Slava mentioned above that do appear to have phenotypic effect on drug resistance, and those are included in the "core" set. See [our documentation on the difference between "core" and "plus"](https://github.com/ncbi/amr/wiki/Interpreting-results#the-scope-column-and-the---plus-option) for a more thorough explanation.

Thanks for using AMRFinderPlus!
Arjun

**Comment by Calebros** [comment]
Hi @evolarjun,

Thank you for the further clarification into this particular instance and for the link.  I was initially confused by the blaEC class being both core and plus, but your explanations have helped greatly.  Thank you for your assistance and for maintaining the tool!
