### ISSUE TITLE
Fail to update database with ubuntu 18.04

### ISSUE THREAD

**Issue by ctSkennerton** [ncbi/amr#20]
I'm trying to install amrfinder in ubuntu and I keep running into a problem when updating the database:

```
sh: 1: set: Illegal option -o pipefail

*** ERROR ***
"common.cpp", line 2742: isRight (execDir, "/")

HOSTNAME: 8d3eaac3c4f1
PWD: /
Progam name:  
Command line: amrfinder -u
```
I understand that the default shell in ubuntu doesn't have that option but I'm not sure how to change that so amrfinder will run.

Below is a docker file that can reproduce this error.
```
FROM ubuntu:18.04

RUN apt-get update && apt-get install -y hmmer ncbi-blast+ git libcurl4-openssl-dev build-essential
RUN git clone https://github.com/ncbi/amr.git && cd amr && make && make install && cd .. && rm -rf amr
RUN amrfinder -u
```

**Comment by evolarjun** [comment]
Unfortunately we didn't test under Ubuntu prior to release to notice the bash-ism. Can you use the previous version while we fix the code?

**Comment by ctSkennerton** [comment]
thanks, I'll give it a try.

**Comment by evolarjun** [comment]
We have a fix on a development version of amrfinder. I cut a temporary branch so if you add `git checkout pipefail_fix` to your commands you should have a temporary fix. We will have a new release with the fix out soon.

This is a development version, but the other differences are related to the `--pgap` option, so as long as you're not using that, it should work for you until we have a new release ready.

**Comment by evolarjun** [comment]
I've just made a new release (v3.6.7) that should resolve this issue.
