### ISSUE TITLE
"Plus" proteins database

### ISSUE THREAD

**Issue by ireneortega** [ncbi/amr#27]
Hi!

I run AMRFinder with the option --plus for Campylobacter, but no virulence genes are found, just AMR and stress genes. How can I know what plus genes are included in that organism?

Thanks.

**Comment by fsislaben** [comment]
Have you browsed the fam.tab file?  CdtA and CdtB are in there.  You can find if your items of interest are included.

**Comment by evolarjun** [comment]
As fsislaben mentioned, we may not have the virulence genes you're looking for in the database. The easiest way to see which genes AMRFinderPlus searches for is to look in the [Pathogen Detection Reference Gene Catalog](https://www.ncbi.nlm.nih.gov/pathogens/isolates#/refgene/).

**Comment by ireneortega** [comment]
All right, I didn't realize that file. Thanks to both of you!
