### ISSUE TITLE
`make install INSTALL_DIR` fails

### ISSUE THREAD

**Issue by hmontenegro** [ncbi/amr#29]
Compiling AMRFinderPlus 3.8.4 from source fails at the `make install INSTALL_DIR=/some/path` step, as **INSTALL_DIR** is not defined in Makefile. 

Using `make install bindir=/some/path` works.

**Comment by evolarjun** [comment]
Argh! Sorry. I had a hard time fixing an issue with the bioconda install on Mac, and in the merge I failed to catch that I had broken the install from source instructions because I redid the way the directories were specified.

I will push a fix soon.

Thanks for reporting!
Arjun

**Comment by evolarjun** [comment]
The most recent commit fixes the issue (https://github.com/ncbi/amr/tree/97e5cc225bf9621ac23fe4faee65c133906de9d1). Though using a custom database directory will print a warning. 

I also updated the documentation to reflect that: https://github.com/ncbi/amr/wiki/Compile-from-source

Thanks again for reporting. The original method should work for you now. So I don't break your fix, setting `bindir` works too.
