### ISSUE TITLE
About gryA mutation in Acinetobacter baumannii

### ISSUE THREAD

**Issue by feihongloveworld** [ncbi/amr#35]
hi sir：
     the S81L mutation of gyrA in Acinetobacter baumannii was not  record in database，
     Acinetobacter baumannii is very import species in clinic, may amrfinder should give a class in amr detection.
thanks.

**Comment by evolarjun** [comment]
At this point we have not curated Acinetobacter baumannii mutations. You can see the list of species for which we've curated mutations in our [documentation of the `--organism` option](https://github.com/ncbi/amr/wiki/Running-AMRFinderPlus#--organism-option) .
