### ISSUE TITLE
Using the antibiotic resistance ontology

### ISSUE THREAD

**Issue by ctSkennerton** [ncbi/amr#36]
Hi, this is a question/feature request rather than an issue: Are there any plans to have integration with the [antibiotic resistance ontology](https://www.ebi.ac.uk/ols/ontologies/aro)? Many of the gene names that are predicted have a corresponding entry but sometimes the formatting isn't always the same, which can make combining the datasets more difficult. Having those names standardized or if AMRFinder reported the antibiotic resistance ontology IDs would be very helpful.

**Comment by evolarjun** [comment]
Sorry for the delay in answering. We regularly exchange data on AMR genes with CARD, but we are an independently curated resource. Because we are independent resources, the content of the databases are different, and sometimes there are conflicts in our naming and gene function determination. 

Could you give some examples so we can see if there are ways to get closer to what you're looking for?

**Comment by ctSkennerton** [comment]
My question wasn't so much about CARD itself but the antibiotic resistance ontology. For example, the term [ARO:3002524 in the antibiotic resistance ontology](https://www.ebi.ac.uk/ols/ontologies/aro/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FARO_3002524) has the name "AAC(2')-Ib" while in the NCBI AMR database it is listed as "aac(2')-Ib" (note the different cases used).

What I'm trying to do is to match the allele/gene names produced by AMRFinder to their corresponding entry in the ontology.

**Comment by ctSkennerton** [comment]
You're right the AME and the beta-lactamases don't have great overlap. At the moment I'm basically doing a name lookup and then going through manually and fixing/merging where it didn't work automatically.

My interest overall is to compare predictions produced by AMRfinder to phenotypic tests done in the lab. Or alternatively, based on phenotypic resistance identify the genes in the genome that contribute to that resistance. My initial thought was to link via allete names and then use the ontology to find the antibiotics to test with in the lab. But it seems like it'll be easier to use the subclass column produced by AMRfinder and use the antibiotic name.

**Comment by evolarjun** [comment]
That would be my approach. We are actively curating the subclass column, but we may have missed things, so if you do see something missing or wrong in that or any other field please let us know.
