### ISSUE TITLE
What to use as database for Galaxy version

### ISSUE THREAD

**Issue by PHemarajata** [ncbi/amr#39]
Hi. It is not clear to me which database files and which format is used for the analysis on Galaxy. I tried uploading some of the files I downloaded from NCBI AMR database but the tool does not recognize any of them.

**Comment by evolarjun** [comment]
Hi,

I'm not very familiar with Galaxy (gave it a try about 10 years ago, but that's about it). By default the STDERR output of AMRFinderPlus should report the version of the software and database used, so you should be able to figure out from there. 

We haven't been involved in connecting AMRFinderPlus with Galaxy, so I'm not sure how it works in your case. You might have more luck asking the admins for your Galaxy server. 

Please let us know what you find out in case other people have the same question. It seems like an obvious question if you're publishing results from a Galaxy analysis, so others might benefit from knowing how you figured it out.

Arjun
