### ISSUE TITLE
install fails

### ISSUE THREAD

**Issue by waalkes** [ncbi/amr#4]
I am trying to install amrfinder as described here (running ubuntu 18.04) but in this step is it failing:

$ ./amrfinder.pl -U
Running ./amrfinder.pl -U
No current AMRFinder database.
Cannot connect to hostname Network is unreachable at ./amrfinder.pl line 258.

The line is:
my $ftp = Net::FTP->new("ftp.ncbi.nlm.nih.gov", Passive => 1) or die "Cannot connect to hostname $@" ;

I can navigate to all the directories from inside a browser on my machine.

ping to ftp.ncbi.nlm.nih.gov times out

ftp gets connection timeout on IPv4 and Network unreachable on IPv6:
$ ftp ftp.ncbi.nlm.nih.gov
ftp: connect to address 130.14.250.7: Connection timed out
Trying 2607:f220:41e:250::11...
ftp: connect: Network is unreachable
ftp> quit

Any help?

**Comment by evolarjun** [comment]
Hmmm... I'm not sure why ftp.ncbi.nlm.nih.gov is unreachable for you. It appears to be up and reachable for me, though it could have been temporarily down. It may also be that there's a firewall blocking ftp in the way.  

If you still can't get through to the FTP site, using HTTP is an option (though not one we have built into AMRFinder yet. We're replacing FTP with HTTP in the major revision currently under development).

Can you connect to https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinder/data/2019-02-08.1/ ?

That's the latest database directory. If you download the contents of that directory manually you can point to it with the -d option to AMRFinder to run with that database. Let me know if that helps.

**Comment by waalkes** [comment]
I do have access that.  I downloaded all the files and then made the database:
$ makeblastdb -in AMRProt -dbtype prot -out AMRProt
I tried using the -d and wouldn't take the directory(full error attached):  
$ ./amrfinder.pl -d /mnt/disk4/labs/salipante/programs/amrfinder -p test_prot.fa
...
ERROR: options not understood: /mnt/disk4/labs/salipante/programs/amrfinder/data
...
ERROR: AMRFinder database files not found
       You can use the -U option to automatically download the latest data
       and install it in the default location
       /mnt/disk4/labs/salipante/programs/amrfinder/data

I got it to work by hard coding the  $database_dir and not using the -d 
$database_dir="/mnt/disk4/labs/salipante/programs/amrfinder/data";

So I think I am good but you probably want to check your -d option

[amrfinder_error.txt](https://github.com/ncbi/amr/files/3082020/amrfinder_error.txt)

**Comment by evolarjun** [comment]
Sorry and Thanks!  I had fixed the bug and not made a new release including the fix.
