### ISSUE TITLE
optimal parameters to start

### ISSUE THREAD

**Issue by fetyj** [ncbi/amr#46]
Hi,
Thanks for this great tool. I'm trying to rule out the absence of resistance genes in some probiotic candidate bacteria so I wonder which parameters seems the optimal one? Is the default one to restrictive for that purpose?
Thank in advance for your help,
Regards,

Fety

**Comment by evolarjun** [comment]
Hi Fety,

I would recommend using the protein and/or combined AMRFinderPlus (which requires an annotation). This increases sensitivity to novel genes in known AMR classes using our curated HMMs. Note that our curators have taken a somewhat restrictive view of what to include in our "core" database. They've tried to avoid genes that are not likely to really be resistance genes, and genes in families that are not likely to have an effect on phenotype in the real world. Also note that our focus has been on pathogens.

The core database consists of genes, and point mutations in select pathogens, that our expert curators believe are likely to be functional, or at least those that someone in public health or surveillance would want to know about. The "plus" section contains some additional genes of interest to our collaborators in public health. These may or may not always be associated with resistance or other phenotypes. Interpretation of the results will be important to understanding likelihood of resistance.

We intend the default search parameters to do a good job at identifying known acquired AMR genes and novel acquired AMR genes in known classes, but there are sure to be efflux pumps and point mutations that we do not cover in the organisms you are looking at. All that is to say that we wouldn't make any promises for fitness in this application, but the default parameters (with combined protein plus nucleotide search) are our best estimate of high sensitivity and accuracy for detection in the set of pathogens we have most experience with (https://www.ncbi.nlm.nih.gov/pathogens/).

I think you will have to be careful about interpretation, but the default search parameters should have high sensitivity for what is in our database. We really don't like to miss things, but we have also found that some other applications will sometimes incorrectly identify resistance genes, and we try to avoid that. 

Not sure how much help I was, but good luck, and let us know if you have more questions.

Arjun

**Comment by fetyj** [comment]
Hi Arjun,
Thanks for the clarifying. It will be very helpfull with some of our strains, we'll deal differently with the other one by using more suitable databases.
Fety
