### ISSUE TITLE
Error in cpp

### ISSUE THREAD

**Issue by TahaAslani** [ncbi/amr#50]
Hi,

I am trying to analyze the gene in a fasta file using this command:

amrfinder -p /beegfs/scratch/tv349/CARD-rgi/MainCV/Run/AMINOGLYCOSIDE-0.fa -o /beegfs/scratch/tv349/AMRFinder/MainCV/Run/outAMINOGLYCOSIDE-0 --threads 48

But it keeps giving me an error message.This is the error message:

^[[1;31m*** ERROR ***^[[0m
"common.cpp", line 2988: mkstemp (templateS) != -1
Stack:
amrfinder(+0x2e34c) [0x55555558234c]
amrfinder(+0x105ac) [0x5555555645ac]
amrfinder(+0x332e7) [0x5555555872e7]
amrfinder(+0x7072) [0x55555555b072]
/lib64/libc.so.6(__libc_start_main+0xf3) [0x1555549e9873]
amrfinder(+0x74f5) [0x55555555b4f5]

Is there anything that I can do?

**Comment by vbrover** [comment]
AMRFinder cannot create a temporary file.
Please check the free space in your temporary directory: ```df /tmp```

What is the version of AMRFinder you are using?

**Comment by evolarjun** [comment]
Hi Taha,

With AMRFinderPlus version 3.9.8 you can change the location of temporary files by setting the TMPDIR environment variable.  For example, if you had sufficient disk space in your home directory, you might do the following before running AMRFinderPlus:

```bash
mkdir ~/tmp
export TMPDIR=~/tmp
amrfinder -p /beegfs/scratch/tv349/CARD-rgi/MainCV/Run/AMINOGLYCOSIDE-0.fa -o /beegfs/scratch/tv349/AMRFinder/MainCV/Run/outAMINOGLYCOSIDE-0 --threads 48
```

Let us know how it goes,
Arjun

**Comment by evolarjun** [comment]
I think this is resolved. Please reopen if it continues to be an issue.
