### ISSUE TITLE
Dealing with software and database version mismatches.

### ISSUE THREAD

**Issue by rpetit3** [ncbi/amr#51]
```
  Running: amrfinder -n AF01.ffn -d amrfinderdb/ -o antimicrobial-resistance/AF01-gene-report.txt --ident_min -1 --coverage_min 0.5 --translation_table 11 --threads 4
  Software directory: '/bactopia/share/bactopia-1.6.x/conda/envs/antimicrobial_resistance-1.6.x/bin/'
  Software version: 3.9.8
  Database directory: 'amrfinderdb'
  Database version: 2021-03-01.1
  
  *** ERROR ***
  Database requires sofware version at least 3.10.1
  To download the latest version to the default directory run: amrfinder -u
```

Hi!

I'm wondering if there are alternatives to updating AMRFinder+ when a version mismatch occurs.

For example, if I'm using `v3.9.8` is there a way to download the last database that was compatible with `v3.9.8` and warn me to say "hey this db is old and you should think about updating AMRFinder+".

Thanks!
Robert

**Comment by evolarjun** [comment]
Hi Robert,

I'm not sure I completely understand why this is hitting you.  If you use an older version of the software and run `amrfinder -u` it should download the latest _compatible_ version of the database. It should also print a warning.

The latest database for a given version is available as the last directory in the URL that matches the first two numbers of the version (https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/VERSION_STRING). E.g., for the AMRFinderPlus version 3.9.8 the latest database would be in https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/3.9/2020-12-17.1/.

E.g., using version 3.9.8: 

```
$ ./amrfinder -u
Running: ./amrfinder -u
Software directory: '/home/aprasad/tmp/'
Software version: 3.9.8
Running: /home/aprasad/tmp/amrfinder_update -d /home/aprasad/tmp/data
Looking up databases at https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/

WARNING: A newer version of the database exists (2021-03-01.1), but it requires a newer version of the software (3.10) to install.
See https://github.com/ncbi/amr/wiki/Upgrading for more information.

Downloading AMRFinder database version 2020-12-17.1 into '/home/aprasad/tmp/data/2020-12-17.1/'
Indexing
Database directory: '/home/aprasad/tmp/data/2020-12-17.1'
Database version: 2020-12-17.1
```

Unless there's a bug I'm not aware of, you should always get the latest compatible version of the database when you use `amrfinder -u`. 

Is there something I'm missing?

**Comment by rpetit3** [comment]
Great news @evolarjun this is a case of user error! You already do what I was suggesting.

Here's what happened. I have my tool [Bactopia](https://bactopia.github.io/), when a user installs it via Conda, the latest version of AMRFinder+ is downloaded, I then use a separate environment in Nextflow to run the analysis, and this may or may not have the same version of AMRFinder+.

So basically I just need to make sure my AMRFinder+ versions are in sync.

Apologies, but also thank you very much for exposing this!

Take care @evolarjun!

**Comment by evolarjun** [comment]
Hi Robert,

Glad it's working the way it's supposed to. Let us know if you have other issues.

Thanks,
Arjun
