### ISSUE TITLE
Error creating a temporary file

### ISSUE THREAD

**Issue by SESchmedes** [ncbi/amr#52]
I keep getting the following error when trying to run amrfinder (3.10.1) - even just running "amrfinder --help". I get this error when trying to run using singularity and conda.

*** ERROR ***
Error creating a temporary file

**Comment by SESchmedes** [comment]
Please disregard. I was able to figure it out with the help of a colleague.

**Comment by vbrover** [comment]
$ amrfinder --help | tail -1
    Temporary directory used is $TMPDIR or "/tmp"

Your ``/tmp`` is probably full.
We will work on making this type of problem to be less frustrating.
