### ISSUE TITLE
Gene not found when used with --organism

### ISSUE THREAD

**Issue by cytang19** [ncbi/amr#54]
Hi, I was working with one Klebsiella pneumoniae genome, when used with --organism "Klebsiella", some genes were not found as compared to without --organism "Klebsiella". I also tested with --organism "Escherichia coli" and the missing genes were actually identified. Note that the genes are confirmed to be present and they are Klebsiella genes. Not sure what causes this issue. Please advise.

Thanks,
CY

ps.: I tested amrfinder version: 3.10.1 and 3.10.5, database version: 2021-03-01.1
command used: `amrfinder -n sample.fasta --plus -o sample.amrfinder.tsv --threads 15 {--organism "Klebsiella"}`

**Comment by vbrover** [comment]
There are genes like _arsC_, _fieF_, _kdeA_ which are common for _Klebsiella_ and are reported by `amrfinder` only if it is run with the option `--report_common`.

Could you send us an example of a Klebsiella gene (FASTA file) which is nor reported by `amrfinder --organism "Klebsiella"`?

**Comment by evolarjun** [comment]
Hi Cy,

As Slava said above, likely what you are seeing is a feature of AMRFinderPlus to hide some genes that are extremely common and not likely to be informative as to phenotype in a given taxonomic group. You can see which genes are skipped for _Klebsiella_ by following this [link to the Pathogen Detection Reference Gene Catalog](https://www.ncbi.nlm.nih.gov/pathogens/refgene/#blacklisted_taxa:Klebsiella). Currently only arsC, kdeA, and fieF. 

The other situation where rows can appear or disappear depending on the `--organism` flag can happen is point mutation detection. AMRFinderPlus only looks for point mutations known in the literature in the taxon indicated by the flag, so if there is a gene in another taxon that is close enough to call point mutations you could get new results by changing the `--organism`, though in practice we haven't found that to be common even between Enterorbacteriaceae. 

One other place where the `--organism` option is used is specific to _Streptococcus_ pbps where divergent sequences are only detected with the option `--organism Streptococcus_pneumoniae`. That is obviously not the case here.

If you are seeing other genes that you expect to find missing, then we may have a problem.  Please let us know what results AMRFinderPlus was missing.

Thanks,
Arjun

**Comment by cytang19** [comment]
I see. The genes that are involved are kdeA and fieF, I’m not aware of this feature. Thanks both for the explanation!
