### ISSUE TITLE
AMRfinderPlus, the tool cannot open fasta file

### ISSUE THREAD

**Issue by Jalalalzanin** [ncbi/amr#56]
Hi everyone,
I am using AMRfinderPlus tool for the first time,  I got an error that the tool unable to open the fasta file  as follows:

Running: amrfinder --plus -n onescaffold.fa -O Streptococcus
Software directory: '/root/miniconda3/bin/'
Software version: 3.10.1
Database directory: '/root/miniconda3/share/amrfinderplus/data/2021-06-01.1'
Database version: 2021-06-01.1
AMRFinder translated nucleotide and mutation search

*** ERROR ***
Cannot open file 'onescaffold.fa'

HOSTNAME: ?
SHELL: /bin/bash
PWD: /root
Progam name:  amrfinder
Command line: amrfinder --plus -n onescaffold.fa -O Streptococcus

I appreciate any advice in advance

**Comment by vbrover** [comment]
Please check whether the FASTA file exists:

    ls /root/onescaffold.fa

**Comment by Jalalalzanin** [comment]
Hi, @vbrover 
Yes I am sure it is there but when the  'ls' command used , my fasta file not listed among the files in the root
Miniconda3-latest-Linux-x86_64.sh  test_both.expected  test_dna.fa         test_prot.fa
miniconda3                         test_dna.expected   test_prot.expected  test_prot.gff
