### ISSUE TITLE
Accumulating database symlinks on /tmp

### ISSUE THREAD

**Issue by oschwengers** [ncbi/amr#58]
Hi, thanks for this great piece of software - we use it a lot!

We recognized that `amrfinder` writes empty files and symlinks to `/tmp` which are not removed after execution and thus accumulate over time. They don't use a ton of space so it's not that much of an issue but still, it might be nice to have them properly removed.

Are there any reasons why these files remain? Otherwise, could this be fixed? These files accumulate on our HPC machines and we're asked to remove them every now and then.

```
$ ls -l /tmp/
-rw-------  1 xyz xyz    0 Aug  6 11:43 Hm4dDh
lrwxrwxrwx  1 xyz xyz   52 Aug  6 11:43 Hm4dDh.db -> /home/xyz/tmp/test-amrfinderplus/db/amrfinderplus/
```

**Comment by evolarjun** [comment]
Hi Oliver,

AMRFinderPlus does write to /tmp (or whatever $TMPDIR is pointing to), but unless the run fails for some reason it should delete the files once the run completes. Persisting them when AMRFinderPlus fails to complete for some reason helps with  debugging, so I hadn't really worried about that.  I do sometimes accumulate files in /tmp during testing, but I haven't seen an issue when running AMRFinderPlus normally.  

Do the files in /tmp persist stick around even when AMRFinderPlus completes successfully? Maybe we've got a bug somewhere.  

Thanks for pointing this out. I wasn't aware that this was an issue for anyone running AMRFinderPlus normally.

Arjun

**Comment by oschwengers** [comment]
Hi Arjun,
I've just double checked the behavior and indeed, the files only remain upon failed executions. A normal execution does not accumulate these files. Sorry for reporting too fast - my fault.
Best regards!

**Comment by vbrover** [comment]
> the files only remain upon failed executions

Do you know why `amrfinder` failed?

**Comment by oschwengers** [comment]
I think for external reasons, like `kill` signals

**Comment by oschwengers** [comment]
Thanks, but that's really not an issue here. AMRFinder is executed by another software tool (Bakta). I'll address this by simply pointing `$TMPDIR` to a subdirectory within a custom temp dir Bakta has control of prior to the AMRFinder execution.

**Comment by evolarjun** [comment]
One quick option that occurs to me is to set TMPDIR to a directory that is automatically deleted. Most cluster management software has built-in functionality for this, but you can also wrap the call to AMRFinderPlus in shell code to create and delete the temporary directory.
