### ISSUE TITLE
Metagenomic assemblies or reads as input?

### ISSUE THREAD

**Issue by Anto007** [ncbi/amr#66]
Hi,

Nice tool! I was wondering if it can accept metagenomic assemblies and genomic/metagenomic read files as inputs as well? The latest version of ResFinder, for example, is definitely capable of handling these type of input files. Thanks!

**Comment by evolarjun** [comment]
Hello Anto007,

Thanks for your kind words. AMRFinderPlus doesn't do assembly, but it should run on assembled contigs from just about anywhere. I don't regularly use it myself on metagenomic assemblies, so I can't speak to the runtime, RAM, or disk requirements, but other people have been using AMRFinderPlus metagenomic assemblies and I haven't heard of problems. If you do have issues please let us know.

As I see it the two primary advantages of AMRFinderPlus over ResFinder are (1) naming accuracy (AMRFinderPlus tells you what to call the gene it found, ResFinder tells you what gene in the database it is most similar to) and (2) sensitive detection of distant homologs in annotated sequence using HMMs. So if you're not planning on annotating assemblies (understandable) and are more interested in finding common genes than exactly what to call them, ResFinder may be a better choice for you.
