### ISSUE TITLE
What exactly does -i -1 do? 

### ISSUE THREAD

**Issue by kristyhoran** [ncbi/amr#69]
I am trying to understand better what the `-i -1` specifically means.. The documentation says 

```
-i <0-1> or --ident_min <0-1> Minimum identity for a blast-based hit hit (Methods BLAST or PARTIAL). -1 means use a curated threshold if it exists and 0.9 otherwise. Setting this value to something other than -1 will override any curated similarity cutoffs.
```
Which I take to mean the the default min identity for a blast or partial match is 0.9 or a curated threshold. Except that I am unsure where to find information about the curated thresholds or how to set them if needed. Are you able to provide me with a little more information about the curated thresholds please? 
I look forward to hearing from you. Many thanks in advance

Cheers
Kristy Horan

**Comment by evolarjun** [comment]
@kristyhoran Also closing this ticket because I think we answered your question. If our answer needs clarification or you have further questions feel free to comment and/or reopen.
