### ISSUE TITLE
Compiling for arm64 systems

### ISSUE THREAD

**Issue by sirselim** [ncbi/amr#72]
Hi team,

Thanks for the great tool. We're currently finding ourselves working a lot with arm-based devices (mainly Nvidia Jetson boards) and hit a snag when trying to build amrfinder. After a bit of tinkering one of my colleagues was able to modify the build flags and we now have it building and running very nicely on several different Jetson devices.

So question: are you interested in a pull request to try and provide a means of architecture detection and flag switching in an attempt to provide support for arm alongside x86_x64 processors? It's quite likely that this would include support for the new M1 Macs as well.

**Comment by evolarjun** [comment]
Hi Miles,

Sure!

I don't have test systems right now (either M1 Mac or Arm-64), so we won't be able to support it ourselves, and I have heard that some other people are using AMRFinderPlus on special purpose devices, though I think they had x86 boxes of some kind, but maybe your work will help others.

I'm very curious. If you can tell me, what are you doing with AMRFinderPlus on Jetson boards? 

Thanks!
Arjun

**Comment by sirselim** [comment]
Hi Arjun, 

My apologies, I thought I had responded but it appears not to have gone through (I was using the GitHub app from my phone...).

I'll try and find some time to make the modifications and test on both arm64 and x86_x64 systems before making a PR.

Happy to share what were doing. For the last few years we have been working on getting Nanopore sequencing running on Nvidia Jetson boards ([GitHub repository](https://github.com/sirselim/jetson_nanopore_sequencing)). One of our aims was building "point of care" pipelines that work offline and are open source. We have put such a pipeline together using some basic QC scripts, Kraken2/Sepia, recentrifuge, and amrfinder - amrfinder was the last piece of the puzzle in terms of arm64 compatibility for the Jetson boards. So the overall process should allow sequencing, classification (and assembly), amr detection and interactive reporting, all in "real-time". The real-time aspect is currently being developed but the rest of the pieces are pretty much in place, we're just working in amrfinder now that we have it building on arm64.

Thanks for the great tool!

Cheers, 
  \- Miles

**Comment by sirselim** [comment]
OK, I have had a go at architecture detection and flag switching. I have added a PR #73.

**Comment by evolarjun** [comment]
Thanks! We'll take a look at https://github.com/ncbi/amr/pull/73.
