### ISSUE TITLE
amrfinder - u issue, Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by skbrimer** [ncbi/amr#74]
Hello NCBI Team!

I was having an issue with updating the amrfinder databases after compiling from the source. I choose this route mostly because I already have the required software installed. In the future I will use the bioconda link, however the issue I ran into was that amrfinder couldn't find `makeblastdb` despite being in my path. 

My solution to the issues was to make a symbolic link from where `makeblastdb` is installed to the `/usr/local/bin` directory. This fixed my issues but I thought maybe someone else could run into this issue so that is the reason for my post. 

I can't think of any reason amrfinder was unable to locate  makeblastdb. I hope this helps and thanks you for your great work!

Sean

**Comment by vbrover** [comment]
`amrfinder` (or `amrfinder_update`) just invokes `makeblastdb` without any path.
What is the output if you run `makeblastdb` form your command line?
Please post the output of your run of `amrfinder` which should update the `amrfinder` databases.

**Comment by skbrimer** [comment]
Wow, I didn't expect this fast of a response! 

Here is the output for `makeblastdb`
```
sean@LEN943:~$ makeblastdb -h
USAGE
  makeblastdb [-h] [-help] [-in input_file] [-input_type type]
    -dbtype molecule_type [-title database_title] [-parse_seqids]
    [-hash_index] [-mask_data mask_data_files] [-mask_id mask_algo_ids]
    [-mask_desc mask_algo_descriptions] [-gi_mask]
    [-gi_mask_name gi_based_mask_names] [-out database_name]
    [-max_file_sz number_of_bytes] [-logfile File_Name] [-taxid TaxID]
    [-taxid_map TaxIDMapFile] [-version]

DESCRIPTION
   Application to create BLAST databases, version 2.7.1+

Use '-help' to print detailed descriptions of command line arguments
```
This is the error I received prior to creating the symbolic link from `/opt/ncbi-blast-2.7.1+/bin/makeblastdb` to the `/usr/local/bin`

```
sean@LEN943:~/Desktop/salmonella/LS21-4590_Sal$ sudo amrfinder --force_update
Running: amrfinder --force_update
Software directory: '/usr/local/bin/'
Software version: 3.10.18
Running: /usr/local/bin/amrfinder_update -d /usr/local/bin/data --force_update
Looking up databases at https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/

*** ERROR ***
Binary 'makeblastdb' is not found.
Please make sure that 'makeblastdb' is in the same directory as 'amrfinder_update' or is in your $PATH.

HOSTNAME: ?
SHELL: /bin/bash
PWD: /home/sean/Desktop/salmonella/LS21-4590_Sal
Progam name:  amrfinder_update
Command line: /usr/local/bin/amrfinder_update -d /usr/local/bin/data --force_update

*** ERROR ***


HOSTNAME: ?
SHELL: /bin/bash
PWD: ?
Progam name:  amrfinder
Command line: amrfinder --force_update
```
Now that is works here is the output for the command. 

```
sean@LEN943:~$ sudo amrfinder -u
[sudo] password for sean: 
Running: amrfinder -u
Software directory: '/usr/local/bin/'
Software version: 3.10.18
Running: /usr/local/bin/amrfinder_update -d /usr/local/bin/data
Looking up databases at https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/
WARNING: '/usr/local/bin/data/2021-09-30.1/' contains the latest version: 2021-09-30.1
Skipping update, use amrfinder --force_update to overwrite the existing database

Database directory: '/usr/local/bin/data/2021-09-30.1'
Database version: 2021-09-30.1
```

Does this information help? Let me know if you need some more!

**Comment by vbrover** [comment]
What if you try
`sudo makeblastdb`
?

**Comment by vbrover** [comment]
I would run
`amrfinder -u -d <database directory>`
without `sudo`.

**Comment by skbrimer** [comment]
I feel like I should just say again. I have the program running and working just fine. I just wanted to let you know in case anyone else ran into this problem. As for you questions, running `sudo makeblastdb` without any options returns the same errors as without sudo

```
sean@LEN943:~$ sudo makeblastdb 
USAGE
  makeblastdb [-h] [-help] [-in input_file] [-input_type type]
    -dbtype molecule_type [-title database_title] [-parse_seqids]
    [-hash_index] [-mask_data mask_data_files] [-mask_id mask_algo_ids]
    [-mask_desc mask_algo_descriptions] [-gi_mask]
    [-gi_mask_name gi_based_mask_names] [-out database_name]
    [-max_file_sz number_of_bytes] [-logfile File_Name] [-taxid TaxID]
    [-taxid_map TaxIDMapFile] [-version]

DESCRIPTION
   Application to create BLAST databases, version 2.7.1+

Use '-help' to print detailed descriptions of command line arguments
========================================================================

Error: Argument "dbtype". Mandatory value is missing:  `String, `nucl', `prot''
Error:  (CArgException::eNoArg) Argument "dbtype". Mandatory value is missing:  `String, `nucl', `prot''

```

I also tried ` amrfinder -u -d /usr/local/bin/data/` and got this error. 

```
*** ERROR ***
AMRFinder update option (-u/--update) only operates on the default database directory. The -d/--database option is not permitted
```

**Comment by evolarjun** [comment]
@skbrimer I think sudo altered your path. Normally I don't run AMRFinderPlus under sudo so I hadn't noticed this. Another option might be to: 

```
sudo PATH=$PATH amrfinder --force_update
```

I'll add a something on the docs for updating the database to indicate this.

Thanks for your report!

**Comment by vbrover** [comment]
> I also tried amrfinder -u -d /usr/local/bin/data/ and got this error.

Sorry.
You can do this:
```
mkdir db
amrfinder_update -d db

```

**Comment by evolarjun** [comment]
Hi again @skbrimer ,

I posted before I saw your last comment...  I bet you're beginning to regret opening this ticket. We're basically spamming you ;-)

I'm stumped.  I thought we had it figured out with the sudo PATH altering thing.  I haven't been able to reproduce the issue otherwise. 

Also I think the `amrfinder -u -d ...` not working and using `amrfinder_update -d` instead thing is a bit confusing. We'll discuss changing that. 

Thanks again,
Arjun

**Comment by skbrimer** [comment]
I think my issue was actually two issues first the `PATH` issue and then the permission issue. I was reading about the default permissions for `/usr/local/bin` which by default is owned by `root` and the users only have read and execute access.

I am still not sure why amrfinder was unable to find BLAST in the path but after adding the symbolic link to the same directory `/usr/local/bin/` it was able to use it. Then I ran into the permission issue when amrfinder was trying to create the `data/` directory for the database(s) since by default the location is write protected. 

All of this makes me wonder if I installed something wrong, however like I said it is working and its great so I am happy :)

**Comment by vbrover** [comment]
> I am still not sure why amrfinder was unable to find BLAST in the path 

If you remove the symbolic link from `/usr/local/bin/` and say `sudo which makeblastdb` then what will you get?

**Comment by skbrimer** [comment]
> If you remove the symbolic link from `/usr/local/bin/` and say `sudo which makeblastdb` then what will you get?

for the command `sudo which makeblastdb` there is no output however when I ask `which makeblastdb` I get `/opt/ncbi-blast-2.7.1+/bin/makeblastdb`


and for reference here is the `echo $PATH` result

```
sean@LEN943:~$ echo $PATH
/home/sean/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/sean/.local/bin:/opt/:/opt/abricate/bin/:/opt/bwa:/opt/SPAdes-3.15.2-Linux/bin:/opt/miniasm:/opt/minimap2:/opt/ncbi-blast-2.7.1+/bin:/opt/prokka/bin/:/opt/ont-guppy-cpu/bin:/opt/bbmap/:/opt/kma:/opt/Harvest/:/opt/seqtk/:/opt/wtdbg2/:/opt/flu-amd:/opt/octoFLU:/opt/fastp
```

**Comment by vbrover** [comment]
> for the command `sudo which makeblastdb` there is no output

And I guess the exit code is not 0.

`sudo` and a regular user have different `PATH`.

**Comment by skbrimer** [comment]
correct, this is all that is returned
```
sean@LEN943:~$ sudo which makeblastdb
sean@LEN943:~$
```
