### ISSUE TITLE
New Mutations

### ISSUE THREAD

**Issue by mweberr** [ncbi/amr#76]
Hi guys,
I am wondering how to propose new mutations in resistance genes which were reported in the last year, but are not yet included in the database ? Is it possible to add a custom user database meanwhile ? Is there a central email to collect suggestions for database updates ?

Thank you for your awesome work!
Best, Michael

**Comment by evolarjun** [comment]
I'm going to close this just because it's been around for a while. We appreciate suggestions to improve our database contents and are happy to answer questions about adding genes/mutations if you have any.  Feel free to re-open this or create new issues if you have further questions.
