### ISSUE TITLE
AMRfinder Update looks at ftp:// site, not https:// link?

### ISSUE THREAD

**Issue by dutchscientist** [ncbi/amr#78]
When I do amrfinder -u on my Ubuntu 18 terminals, they fail after a long wait. I also have the same setup on some Virtualbox Ubuntu 18 stations, and the only difference I notice is that the terminals try to download from **ftp://**ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/, while the successful ones use **https://**ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/

The program is up to date, version 3.10.21. The full readout of the failing stations is (username replaced by <me>):

Running: amrfinder --force_update
Software directory: '/home/<me>/miniconda3/bin/'
Software version: 3.10.21
The number of threads cannot be greater than 2 on this computer
The current number of threads is 4, reducing to 2
Running: /home/<me>/miniconda3/bin/amrfinder_update -d /home/<me>/miniconda3/share/amrfinderplus/data --force_update
Looking up databases at ftp://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/

Any idea how this can be repaired? Have already deinstalled/reinstalled via Conda.

**Comment by vbrover** [comment]
Can you do this command in the environment where you run `amrfinder -u`?

    curl ftp://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/

**Comment by evolarjun** [comment]
@dutchscientist My guess is you may be using different versions of the software on the two different places.  The most recent release [3.10.21](https://github.com/ncbi/amr/releases/tag/amrfinder_v3.10.21) switched from using HTTPS to FTP to reduce our reliance on web server behavior that we don't have control over.  Version 3.10.20 still uses HTTPS. That is the only difference between them. Is it possible there are firewall rules blocking FTP access (ports 20 and 21)?

**Comment by vbrover** [comment]
Also could you please run this and send us the contents of the `aa` file:

    amrfinder -u --log aa --debug

**Comment by dutchscientist** [comment]
> Can you do this command in the environment where you run `amrfinder -u`?
> 
> ```
> curl ftp://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/
> ```

The effect is the same: no response. I have checked with nmap, and it says ports 20 and 21 are filtered?

**Comment by dutchscientist** [comment]
I assume the "Progam name: amrfinder_update" is a typo somewhere in the program ;-)

**Comment by dutchscientist** [comment]
> Could you also try:
> curl --ftp-pasv ftp://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/

curl: (28) Failed to connect to ftp.ncbi.nlm.nih.gov port 21 after 215530 ms: Connection timed out

I'll get in touch with IT. These are virtual computers running on server hardware, and I wouldn't be surprised if there is some firewall activity happening. 

Maybe a suggestion to use FTP as the first update call, and HTTPS as the backup if the first fails?

**Comment by evolarjun** [comment]
We'll work on a fix. In the meantime you can install the previous version (3.10.20) which functionally identical except for the change in protocol for database updates.  Since you're using conda it should be easy to install version 3.10.20 like this:

```
conda install -y -c bioconda -c conda-forge ncbi-amrfinderplus=3.10.20
```
