### ISSUE TITLE
Don't put databases in the bin/ folder

### ISSUE THREAD

**Issue by tseemann** [ncbi/amr#8]
```
% amrfinder_update
Running amrfinder_update
Dowloading AMRFinder database version 2019-07-10.1 into
   /home/miniconda3/envs/ncbi-amrfinderplus_env/bin/data/2019-07-10.1/
Indexing
```

It is bad form to put non-executables in the `bin/` folder.
Could you use `/share/data` instead?

**Comment by evolarjun** [comment]
You're absolutely right. That is in the plans for the next release, which should be "beta" and put things in the right places.

**Comment by evolarjun** [comment]
So this should be resolved in a relatively quick-n-dirty way with the newest release 3.1.1b with an option to make "DEFAULT_DB_DIR=/wherever/you/want/it" which hard-codes the default database directory in the source code.  We also altered the bioconda build script to make this go in a sensible place there. $PREFIX/share/amrfinderplus/data.

(Note this bugged me and I wanted to fix it before we finally finish our testing, so the current 3.1.1b release is still not fully tested to our satisfaction)

Our plan is to set this via a configuration file.

**Comment by tseemann** [comment]
@evolarjun has this bug regressed?
latest conda putting it in bin/ again?
```
/scratch/punim0401/miniconda3/envs/amrfinderplus_env/bin/data/
0 drwxr-sr-x 2 torsten punim0401 193486110 Nov  7 09:27 2019-10-30.1
```
