### ISSUE TITLE
AMRfinderplus Installed with Bioconda, version=3.10.5 

### ISSUE THREAD

**Issue by yuzie0314** [ncbi/amr#81]
Dear the authors,

I found that if I installed with Bioconda from your tutorial document, the 'amrfinder -u' won't work smoothly. Next, I checked the version on my end and the version of amrfinder is 3.10.5, so I used your latest binary files to build the environment and everything are good through the test file.
Hope you take some time to update the amrfinder version in bioconda, just so you know.

HTH and thanks in advance !
Zorya

**Comment by aldertzomer** [comment]
Experiencing the same. 3.10.14 is the latest on conda, the database requires 3.10.16. 

(base) root@lp0106:~# amrfinder -u
Running: amrfinder -u
Software directory: '/usr/local/anaconda/bin/'
**Software version: 3.10.14**
Running: /usr/local/anaconda/bin/amrfinder_update -d /usr/local/anaconda/share/amrfinderplus/data
Looking up databases at https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/
WARNING: '/usr/local/anaconda/share/amrfinderplus/data/2021-12-21.1/' contains the latest version: 2021-12-21.1
Skipping update, use amrfinder --force_update to overwrite the existing database

Database directory: '/usr/local/anaconda/share/amrfinderplus/data/2021-12-21.1'
Database version: 2021-12-21.1

*** ERROR ***
Database requires sofware version at least 3.10.16
To download the latest version to the default directory run: amrfinder -u

HOSTNAME: ?
SHELL: /bin/bash
PWD: /root
Progam name:  amrfinder
Command line: amrfinder -u

**Comment by jdmccauley** [comment]
Hi all,

I found this issue since I was experiencing the same problem. I can confirm that the database only updates when `ncbi-amrfinderplus` is installed when the `conda-forge` channel is added (version 3.10.24). Otherwise, `ncbi-amrfinderplus`, as of today, is installed at version `3.10.5` when using the `bioconda` channel alone and the database refuses to update with that version.

**Comment by evolarjun** [comment]
I updated the installation instructions to be `conda install -y -c bioconda -c conda-forge ncbi-amrfinderplus` (https://github.com/ncbi/amr/wiki/Install-with-bioconda) so hopefully people won't have this problem any more. Thanks to @yuzie0314  and @aldertzomer for reporting your issues and to @jdmccauley that he saw the same issue we saw and our fix worked for him.  Please let us know if anyone is still having problems with this.
