### ISSUE TITLE
GFF file mismatch

### ISSUE THREAD

**Issue by dhiru16** [ncbi/amr#82]
I used the faa and gff files generated from prokka and the error is gff files mismatch
<img width="1509" alt="Screen Shot 2022-04-18 at 6 39 05 PM" src="https://user-images.githubusercontent.com/96434814/163888461-367aa65a-1900-4cdf-bef8-c8b52fb32158.png">

**Comment by vbrover** [comment]
Please try https://github.com/ncbi/amr/wiki/Tips-and-tricks#using-prokka-or-RAST-gff-files-with-amrfinderplus

**Comment by evolarjun** [comment]
@dhiru16  Hopefully @vbrover 's advice fixed your issue. I'm going to close this ticket, but if you're still having a problem please reopen.

Thanks!
Arjun
