### ISSUE TITLE
tet(O/32/O)

### ISSUE THREAD

**Issue by kalilamali** [ncbi/amr#83]
Hi,
I was looking at both [tet_O_32_O.txt](https://github.com/ncbi/amr/files/8537658/tet_O_32_O.txt) genes in ResFinderdb and in AMRFinderPlusdb.
They are substantially different. Does the curatorial team have any insights on why?
Best,
Karen Loaiza.

**Comment by feldgard** [comment]
Karen,

I can't comment as to why ResFinderdb included the protein it did (however, we call their sequence as original tet(O/32/O)), but NCBI's Reference Gene Catalog includes a protein which is nearly identical to the original tet(O/32/O) described in https://pubmed.ncbi.nlm.nih.gov/15728946/. 

Our protein was added at the request of Dr. Karen Scott (Aberdeen, UK). Given the broad identity cutoffs used for tet genes, this protein was considered sufficient and was used.

Mike Feldgarden
Pathogen Detection, NCBI/NLM/NIH

**Comment by kalilamali** [comment]
Thank you for the quick answer.
