### ISSUE TITLE
add gene accessions in fam.tab

### ISSUE THREAD

**Issue by crarlus** [ncbi/amr#93]
I would appreciate if there were more fields in the file fam.tab  - in particular all available gene accessions. This would be helpful for matching amr type, class, etc. information from gff files (generated by prokka, bakta, etc.). So far I can only match the gene_name which is not unambigous.

A fasta header in AMR_CDS looks like this:
```
>0|EAC4468893.1|AAAIJS010000026.1|1|1|emrC_Lis|emrC_Lis|multidrug_efflux_transporter_outer_membrane_subunit_EmrC AAAIJS010000026.1:2413-2027
```
It contains several accessions.

The file fam.tab has the following column headers:
```
$ tsvheader fam.tab                                                
1: #node_id
2: parent_node_id               
3: gene_symbol  
...
14: type
15: subtype
16: class
17: subclass
```
I would appreciate more columns with the accesions given in AMR_CDS 

Thanks
Carlus

**Comment by evolarjun** [comment]
Hi Carlus,

`fam.tab` is designed for internal use for AMRFinderPlus, it's not really designed for public consumption (though people do).

I think what would help you is the Reference Gene Catalog. A web interface is at https://www.ncbi.nlm.nih.gov/pathogens/refgene, and the latest file behind the web interface is available from https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/latest/ReferenceGeneCatalog.txt

In that tab-delimited file every row is a gene or point mutation, and every column is metadata about that gene/point mutation including lots of accessions. 

"Family" information, if that's really what you're after, is in the Reference Gene Hierarchy (Web interface: https://www.ncbi.nlm.nih.gov/pathogens/genehierarchy, and latest tab-delimited text file at https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/latest/ReferenceGeneHierarchy.txt)

Those files were designed with public use in mind, so they contain additional potentially useful information not needed for AMRFinderPlus, and the formatting is a bit nicer.

Let me know if either of those files don't satisfy your needs.

Arjun

**Comment by evolarjun** [comment]
I forgot to mention there's a fairly new [download dataset](https://www.ncbi.nlm.nih.gov/pathogens/pathogens_help/#refgene-access-download)  function in the [Reference Gene Catalog web interface](https://www.ncbi.nlm.nih.gov/pathogens/refgene) that should get you a FASTA file of protein and/or nucleotide sequence.  Since it's new I'd love any feedback about the utility.

Thanks!
Arjun

**Comment by crarlus** [comment]
Thanks, I had forgotten about the Reference Gene Catalog. This is extactly what I need. Thx
