### ISSUE TITLE
a bug maybe? only the first one could be correctly annotated when multiple copies of amr exist

### ISSUE THREAD

**Issue by fengyuchengdu** [ncbi/amr#94]
Dear all,

The amplification of amr genes seems common and I found that for a sequence containing 3 copies of blaOXA genes, however, only the first one could be correctly labelled as OXA-1041, the rest two could not. 

Given that the nucleotide sequences of these 3 blaOXA were identical, this result seemed weird. 

I've attached a simple fasta example and the amrfinderplus result to this example in the zip files.
[test.zip](https://github.com/ncbi/amr/files/9228067/test.zip)
[test_result.zip](https://github.com/ncbi/amr/files/9228072/test_result.zip)

**Comment by vbrover** [comment]
> only the first one could be correctly labelled as OXA-1041, the rest two could not.

This is exactly what `amrfinder` is reporting: the first gene is the "ALLELE" blaOXA-1041, whereas the next two genes only **belong to the family** blaOXA. This information is in the columns "Gene symbol" and "Method".

See https://github.com/ncbi/amr/wiki/Interpreting-results#the-method-column.

**Comment by fengyuchengdu** [comment]
3 blaOXA genes are literally identical and why they weren't all labelled "ALLELE" blaOXA-1041?

**Comment by vbrover** [comment]
> 3 blaOXA genes are literally identical and why they weren't all labelled "ALLELE" blaOXA-1041?

Only 100% identity and 100% coverage (in other words, identical sequence) is considered to be an "allele".

**Comment by evolarjun** [comment]
Hi @fengyuchengdu ,

I took a look at the sequences you uploaded and I can reproduce the issue you're reporting. I'm not yet sure what is going on. We'll take a closer look and get back to you.

Thanks for reporting!
Arjun

**Comment by vbrover** [comment]
Thank you for posting the bug!
It will be fixed in software version 3.10.35.

**Comment by fengyuchengdu** [comment]
Great ! many thanks to you all.

**Comment by evolarjun** [comment]
Fixed in [version 3.10.36](https://github.com/ncbi/amr/releases/tag/amrfinder_v3.10.36).

Thanks again!
