### ISSUE TITLE
How to request addition of virulence genes?

### ISSUE THREAD

**Issue by kapsakcj** [ncbi/amr#96]
Hi Arjun et al.,

I'd like to request the addition of Vibrio cholerae virulence genes, specifically cholera toxin genes `ctx` like `ctxA` and `ctxB` to the amrfinderplus database, or perhaps the `--organism` option for V cholerae.

Is there some kind of formal process for requesting this? I saw [this page](https://www.ncbi.nlm.nih.gov/pathogens/submit-beta-lactamase/) that is specific for beta lactamase alleles, but unsure about other kinds of genes/alleles.

I'm curious as to what other requirements there might be as well - if publications and/or wet lab confirmation is required and how to best go about providing this

I'd like to include the CDC reference lab (Enteric Diseases Lab Branch, LYVE reference lab [LYVE = Listeria, Yersinia, Vibrio, and Enterobacteraciae]) that is responsible for Vibrio in this discussion, as they are the experts in this area and know much more about this pathogen than I do.

Curtis

**Comment by evolarjun** [comment]
Hi Curtis,

Traditionally we've had working groups made up of domain experts submit suggested additions for our curators to add virulence and stress resistance genes, though our Pathogen Detection curators sometimes take advantage of work done for RefSeq curation to also include salient genes from that effort. 

Until we know more we can't make any promises for how quickly the output of such working groups makes it through curation into the AMRFinderPlus database. Our curation resources are somewhat limited. I'll reach out privately to get more information and see what we can do to help. We continue to work with you and the CDC on other issues and we're happy to add new collaborations that can be mutually beneficial.

Thanks,
Arjun

**Comment by kapsakcj** [comment]
Thanks for adding ctxA & ctxB to the database! Appreciate the fast turnaround!

I was able to successfully ID those 2 genes in a few Vibrio cholerae genomes with the updated version of the code & updated database

🎉
