### ISSUE TITLE
Incorrect Gene Symbol in Output?

### ISSUE THREAD

**Issue by cizydorczyk** [ncbi/amr#97]
When I run AMRFinderPlus on an S. aureus genome, one of the output lines reads:

`JMB00937	fig|6666666.952341.peg.4515	abc-f	ABC-F type ribosomal protection protein	core	AMR	AMR	MACROLIDE	MACROLIDE	HMM	642	655	95.11	35.40	644	WP_063854496.1	ABC-F type ribosomal protection protein	NF000355.3	ABC-F type ribosomal protection protein`

Through manual checking of what gene "abc-f" is, I found that in the database, this gene (based on reference accession) is actually "optrA" -- so why does AMRFinderPlus report the gene symbol as "abc-f"?

Or am I fundamentally misunderstanding what is being reported here and how?

Thank you,
Conrad

**Comment by vbrover** [comment]
WP_063854496.1 would have been reported as _optrA_, but your protein JMB00937 is sufficiently dissimilar from WP_063854496.1 and is reported as the parent family of _optrA_ which is _abc-f_ using an HMM.

**Comment by evolarjun** [comment]
Hi Conrad,

To elaborate a little on what Slava wrote above, AMRFinderPlus identified the gene you are interested in as a likely member of the abc-F family by the HMM [NF000355.3](https://www.ncbi.nlm.nih.gov/pathogens/hmm/#hmm_accession:NF000355.3) which was designed to selectively identify even distant members of the family. You can see more about the other genes in the abc-F family in the Reference Gene Hierarchy <https://www.ncbi.nlm.nih.gov/pathogens/genehierarchy/#abc-F>. AMRFinderPlus reports the closest hit in the reference database (if there is one found by BLAST) which is [WP_0638544936.1](https://www.ncbi.nlm.nih.gov/pathogens/refgene/#WP_0638544936.1) to give people as much information as it can even though the hit is quite a bit below the cutoffs for what AMRFinderPlus would call the optrA gene.  

BLAST only aligned the sequence called JMB00937 to 35% of the reference sequence  ([WP_0638544936.1](https://www.ncbi.nlm.nih.gov/pathogens/refgene/#WP_0638544936.1)) at 95% identity.  Without knowing more about the sequence I can't say that much more than that it is distantly related to anything in our reference database, but it still met the requirements of the curated HMM created to selectively identify all members of the abc-F family.  

I'm not sure if it will help, but you can also check out the [Interpreting results](https://github.com/ncbi/amr/wiki/Interpreting-results) section of our documentation for more information on how to interpret the output of AMRFinderPlus. 

Arjun

**Comment by cizydorczyk** [comment]
Great, thank you for the explanation -- makes sense now.

Conrad
